package homework_3;

public enum Position {
    INSIDE_TAG,
    INSIDE_COMMENT_WITH_SINGLE_QUOTES,
    INSIDE_COMMENT_WITH_DOUBLE_QUOTES,
    BETWEEN_TAGS,
    INSIDE_SCRIPT_TAG,
    INSIDE_STYLE_TAG,
    ENTITY_CODE

}
