package homework_3;

public final class TagList {
    public static final String[][] ignoreTags = {
            //A
            {"a",           "false"},
            {"abbr",        "false"},
            {"acronym",     "false"},
            {"address",     "false"},
            {"applet",      "false"},
            {"area",        "false"},
            {"article",     "false"},
            {"aside",       "false"},
            {"audio",       "false"},
            //B
            {"b",           "false"},
            {"base",        "false"},
            {"basefont",    "false"},
            {"bdi",         "false"},
            {"bdo",         "false"},
            {"bgsound",     "false"},
            {"blockquote",  "false"},
            {"big",         "false"},
            {"body",        "false"},
            {"blink",       "false"},
            {"br",          "false"},
            {"button",      "false"},
            //C
            {"canvas",      "false"},
            {"caption",     "false"},
            {"center",      "false"},
            {"cite",        "false"},
            {"code",        "false"},
            {"col",         "false"},
            {"colgroup",    "false"},
            {"command",     "false"},
            {"comment",     "false"},
            //D
            {"datalist",    "false"},
            {"dd",          "false"},
            {"del",         "false"},
            {"details",     "false"},
            {"dfn",         "false"},
            {"dir",         "false"},
            {"div",         "false"},
            {"dl",          "false"},
            {"dt",          "false"},
            //E
            {"em",          "false"},
            {"embed",       "false"},
            //F
            {"fieldset",    "false"},
            {"figcaption",  "false"},
            {"figure",      "false"},
            {"font",        "false"},
            {"form",        "false"},
            {"footer",      "false"},
            {"frame",       "false"},
            {"frameset",    "false"},
            //H
            {"h1",          "false"},
            {"h2",          "false"},
            {"h3",          "false"},
            {"h4",          "false"},
            {"h5",          "false"},
            {"h6",          "false"},
            {"head",        "false"},
            {"header",      "false"},
            {"hgroup",      "false"},
            {"hr",          "false"},
            {"html",        "false"},
            //I
            {"i",           "false"},
            {"iframe",      "false"},
            {"img",         "false"},
            {"input",       "false"},
            {"ins",         "false"},
            {"isindex",     "false"},
            //K
            {"kbd",         "false"},
            {"keygen",      "false"},
            //L
            {"label",       "false"},
            {"legend",      "false"},
            {"li",          "false"},
            {"link",        "false"},
            //M
            {"main",        "false"},
            {"map",         "false"},
            {"marquee",     "false"},
            {"mark",        "false"},
            {"menu",        "false"},
            {"meta",        "false"},
            {"meter",       "false"},
            //N
            {"nav",         "false"},
            {"nobr",        "false"},
            {"noembed",     "false"},
            {"noframes",    "false"},
            {"noscript",    "false"},
            //O
            {"object",      "false"},
            {"ol",          "false"},
            {"optgroup",    "false"},
            {"option",      "false"},
            {"output",      "false"},
            //P
            {"p",           "false"},
            {"param",       "false"},
            {"plaintext",   "false"},
            {"pre",         "false"},
            {"progress",    "false"},
            //Q
            {"q",           "false"},
            //R
            {"rp",          "false"},
            {"rt",          "false"},
            {"ruby",        "false"},
            //S
            {"s",           "false"},
            {"samp",        "false"},
            {"script",      "true"},
            {"section",     "false"},
            {"select",      "false"},
            {"small",       "false"},
            {"span",        "false"},
            {"source",      "false"},
            {"strike",      "false"},
            {"strong",      "false"},
            {"style",       "true"},
            {"sub",         "false"},
            {"summary",     "false"},
            {"sup",         "false"},
            //T
            {"table",       "false"},
            {"tbody",       "false"},
            {"td",          "false"},
            {"textarea",    "false"},
            {"tfoot",       "false"},
            {"th",          "false"},
            {"thead",       "false"},
            {"time",        "false"},
            {"title",       "false"},
            {"tr",          "false"},
            {"tt",          "false"},
            //U
            {"u",           "false"},
            {"ul",          "false"},
            //V
            {"var",         "false"},
            {"video",       "false"},
            //W
            {"wbr",         "false"},
            //X
            {"xmp",         "false"},
    };
}
